### ISSUE TITLE
Support ES module import in browser

### ISSUE THREAD

**Issue by DanielHabenicht** [elringus/bootsharp#53] opened 2022-04-29 09:04 UTC
Hi again, 

I tested the library with angular and it is running into an error: 
```bash
universalModuleDefinition:1 Uncaught ReferenceError: global is not defined
    at universalModuleDefinition:1:1
    at Object.9424 (universalModuleDefinition:1:1)
    at __webpack_require__ (bootstrap:19:1)
    at Module.1896 (home.component.html:14:263)
    at __webpack_require__ (bootstrap:19:1)
    at Module.721 (universalModuleDefinition:1:1)
    at __webpack_require__ (bootstrap:19:1)
    at Module.23 (app.component.html:6:8)
    at __webpack_require__ (bootstrap:19:1)
    at Module.8835 (environment.ts:16:71)
```

Which is expected as the angular team came to the conclusion to not support global in their webpack build for broad compatibility. https://github.com/angular/angular-cli/issues/9827#issuecomment-369578814

I think this library should not rely on some other process to supply the variable.
So going forward you could use: 
- globalThis: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis
- polyfill it: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis#search_for_the_global_across_environments

Workaround is adding `(window as any).global = window;` to `polyfill.ts`

**Comment by Elringus** [comment] 2022-04-29 13:27
If it's that line, can you please test if the following will work with angular:

```
factory(module.exports, global || window); 
```

**Comment by DanielHabenicht** [comment] 2022-04-29 13:59
It does not work, because global is not defined. You would have to check if it exists before: 

```js
var getGlobal = function () {
  if (typeof self !== 'undefined') { return self; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  throw new Error('unable to locate global object');
};

factory(module.exports, getGlobal()); 
```

**Comment by Elringus** [comment] 2022-04-29 14:05
Or should it be `global ?? window`.

**Comment by DanielHabenicht** [comment] 2022-04-29 14:10
You can try it out in your own web browser, just open the Developer Tools and navigate to the console: 
![image](https://user-images.githubusercontent.com/13590797/165961262-17446a49-4db2-4efb-83d5-8afec4cb7dc1.png)

**Comment by Elringus** [comment] 2022-04-29 14:16
Do you have any idea how we can make an automated test for this without involving angular?

**Comment by DanielHabenicht** [comment] 2022-04-29 14:19
Execute the module in a browser context. 
This could be a way: https://www.sitepoint.com/using-es-modules/#:~:text=Safari%2C%20Chrome%2C%20Firefox%20and%20Edge,Here's%20what%20they%20look%20like.&text=Simply%20add%20type%3D%22module%22,executing%20each%20module%20only%20once.

Otherwise I think there is no way around implementing it inside an example project. 
Which would also be a way to test it.

**Comment by Elringus** [comment] 2022-04-29 14:26
I'm currently using the library in react, no issues here.

**Comment by DanielHabenicht** [comment] 2022-04-29 14:39
I tried it out with stencil now, other error: 
```bash
index-c37bab2d.js:2903 TypeError: Cannot set properties of undefined (setting 'dotnet')
    at app-home.entry.js:10:21
    at app-home.entry.js:11:3 undefined
```

**Comment by Elringus** [comment] 2022-04-29 14:46
I think I was able to reproduce this in hello world sample with the browser module as you've suggested:

```html
<!DOCTYPE html>

Open console (Ctrl+Shift+I) to see the output.


<script type="module">
    import * as dotnet from './Project/bin/dotnet.js'

    dotnet.HelloWorld.GetHostName = () => "Browser";

    window.onload = async function () {
        await dotnet.boot();
        const guestName = dotnet.HelloWorld.GetName();
        console.log(`Welcome, ${guestName}! Enjoy your global space.`);
    };

</script>
```

— but using the getGlobal() doesn't seem to help:

```js
    var getGlobal = function () {
        if (typeof self !== 'undefined') { return self; }
        if (typeof window !== 'undefined') { return window; }
        if (typeof global !== 'undefined') { return global; }
        throw new Error('unable to locate global object');
    };
    if (typeof exports === 'object' && typeof exports.nodeName !== 'string')
        factory(module.exports, getGlobal());
    else factory(root.dotnet, root);
```

**Comment by DanielHabenicht** [comment] 2022-04-29 14:59
I think this is related: https://github.com/umdjs/umd/issues/127

**Comment by Elringus** [comment] 2022-04-29 16:11
I've added browser-es sample for testing (not working right now): https://github.com/Elringus/DotNetJS/blob/main/Samples/HelloWorld/browser-es.html

Not sure what's the best approach to solve this (producing 2 libraries is not optimal, as it will require a lot of extra logic in C# packer). Guess the best workaround for now is polyfilling `global` on the consumer side. Will appreciate any suggestions.

**Comment by DanielHabenicht** [comment] 2022-04-29 16:59
Angular also uses Webpack under the hood. 
But alright you already changed the title of the issue to reflect on the ES module issue.

**Comment by Elringus** [comment] 2022-04-29 17:32
Maybe angular is bundled differently, without static linking the deps? I mean, if bundle already has all the imports resolved/linked internally at build time, it shouldn't matter which import mechanism each individual dependency uses when the bundle is imported at runtime, right?

**Comment by DanielHabenicht** [comment] 2022-04-29 17:34
Well yes angular is already using esm modules. 
Would you be open to including the polyfill for `getGlobal` anyway?

**Comment by Elringus** [comment] 2022-04-29 17:41
> Would you be open to including the polyfill for `getGlobal` anyway?

If it'll solve the issue, sure. I've already tried doing that actually, but it didn't work, because we also need to share that global with dotnet/blazor internal stuff. But maybe I've missed something.

**Comment by DanielHabenicht** [comment] 2022-04-29 18:33
> If it'll solve the issue, sure. I've already tried doing that actually, but it didn't work, because we also need to share that global with dotnet/blazor internal stuff. But maybe I've missed something.

It is at least solving the issue for angular, as angular seems to use a different way for importing the module. 

For the import of module to work we would have to set `this` to `window` in this code of `dotnet.js`: 
```js
!(function (e, t) {
    "object" == typeof exports && "object" == typeof module
        ? (module.exports = t())
        : "function" == typeof define && define.amd
        ? define([], t)
        : "object" == typeof exports
        ? (exports.dotnet = t())
        : (e.dotnet = t());
})(this, () => // <== Here
...
```

**Comment by Elringus** [comment] 2022-04-29 20:30
I've tried replacing `this` to `window`, but it returned `Uncaught TypeError: dotnet.HelloWorld is undefined`.

Regarding angular, do you mean it's not related with the browser-es sample? In this case we'd need a minimal repro (without angular) as a starting point. Ideally, an automated test or at least a sample for manual testing.

**Comment by Elringus** [comment] 2022-04-29 20:47
I'm also not against dropping UMD target if there is a way to make it work with both CommonJS (require) and ES (import) in all the environments. Other UMD scenarios (global script import in browsers and AMD) are not that common nowadays, afaik.

**Comment by Aloento** [comment] 2022-04-30 16:34
In my browser env, no `global` is defined, only `globalThis`

**Comment by Aloento** [comment] 2022-04-30 16:36
> I'm also not against dropping UMD target if there is a way to make it work with both CommonJS (require) and ES (import) in all the environments. Other UMD scenarios (global script import in browsers and AMD) are not that common nowadays, afaik.

If I were to do it, I would just write it all as an ES module and then polyfill it if needed.

**Comment by Elringus** [comment] 2022-04-30 16:50
> If I were to do it, I would just write it all as an ES module and then polyfill it (like Babel) if needed.

The thing is we have [autogenerated mono wasm JS wrapper](https://github.com/Elringus/DotNetJS/blob/main/JavaScript/dotnet-runtime/native/dotnet.js) and then our own [runtime module](https://github.com/Elringus/DotNetJS/tree/main/JavaScript/dotnet-runtime/src). Both are [bundled with webpack](https://github.com/Elringus/DotNetJS/blob/main/JavaScript/dotnet-runtime/webpack.config.js) on top of which C# packer emits [UMD initialization template](https://github.com/Elringus/DotNetJS/blob/main/DotNet/Packer/LibraryGenerator/LibraryTemplate.cs). As it currently stands, we have to first figure how to configure webpack to produce a module that can be imported as both ES and CommonJS in all the environments and then update the packer initialization template.

**Comment by Aloento** [comment] 2022-04-30 16:54
I haven't had a chance to read your code yet, but in my experience, it can be broken down into two steps.
1, generate JS (ES6) code by template
2, depending on the configuration to let the packaging tool (Webpack) handle it (e.g. polyfill and minimization)

**Comment by Elringus** [comment] 2022-04-30 16:58
> depending on the configuration 

We have to produce a single library, that should support both ES and CommonJS scenarios.

**Comment by Aloento** [comment] 2022-04-30 17:06
You should allow the user to define a configuration in the C# project configuration file, such as 
```xml
<JSFormat> 
  esm / amd
</JSFormat>
```

UMD is too big and generates a lot of unnecessary code, as well as ESM would be better if the user is using a newer environment.

**Comment by Elringus** [comment] 2022-04-30 17:09
UMD templates are not big at all, literally about 10 lines: https://github.com/umdjs/umd/blob/master/templates

I would like to support all scenarios with a single library, if possible. After all, it's already working, except this one particular case with ES in browser.

**Comment by Aloento** [comment] 2022-04-30 17:12
ESM modules have been supported since NodeJS 12.
And common packaging tools (eg webpack) can escape cjs modules.

**Comment by Elringus** [comment] 2022-04-30 17:21
Right, but it's required in some environments, eg vscode won't work otherwise.

**Comment by Aloento** [comment] 2022-04-30 17:23
> Right, but it's required in some environments, eg vscode web extensions won't work otherwise.

So like I said, you generate JS with the latest write-ups and then let the user choose what to do with them.

**Comment by Elringus** [comment] 2022-04-30 17:31
In that sense it's already working like this. You can consume current library, post-process it with a bundler (webpack/rollup) and it will work anywhere. This issue is about importing the library as ES module directly in the browser w/o any post-processing.

**Comment by Aloento** [comment] 2022-04-30 17:38
To check env, just:
```js
const isBrowser =
  typeof window !== "undefined" && typeof window.document !== "undefined";

const isNode =
  typeof process !== "undefined" &&
  process.versions != null &&
  process.versions.node != null;

const isWebWorker =
  typeof self === "object" &&
  self.constructor &&
  self.constructor.name === "DedicatedWorkerGlobalScope";

const isJsDom =
  (typeof window !== "undefined" && window.name === "nodejs") ||
  (typeof navigator !== "undefined" &&
    (navigator.userAgent.includes("Node.js") ||
      navigator.userAgent.includes("jsdom")));

const isDeno = typeof Deno !== "undefined" && typeof Deno.core !== "undefined";
```

**Comment by DanielHabenicht** [comment] 2022-05-01 17:13
The "problem" with web modules (ES) is that they are incompatible with older package runtimes as they add the `export` keyword which may not be supported. 

So, I support @Aloento view of generating an ES module first and then using rollup to create UMD/CommonJs, because generating them from ES modules is easy whereas generating ES modules from UMD is not feasible. 

But in the end this is way more work than any of us should invest for this problem. 
The great thing is I found this PR: https://github.com/umdjs/umd/issues/124 
Which suggests the following edit: 

```diff
+var getGlobal = function () {
+    if (typeof self !== "undefined") {
+        return self;
+    }
+    if (typeof window !== "undefined") {
+        return window;
+    }
+    if (typeof global !== "undefined") {
+        return global;
+    }
+    throw new Error("unable to locate global object");
+};
+var global = getGlobal();
...
-})(this, () =>
+})(typeof self !== "undefined" ? self : this, () =>
```

Making it work in angular, and at least loading as web module: 
```html
<script type="module">
    import * as dotnet from "./Project/bin/workaround.js";

    window.onload = async function () {
        await window.dotnet.boot();
        const guestName = window.dotnet.HelloWorld.GetName();
        console.log(`Welcome, ${guestName}! Enjoy your global space.`);
    };
</script>
```
But running into an error: 
```bash
dotnet.js:10763 Uncaught (in promise) ReferenceError: bodyJs is not defined
    at Object.bind_method (dotnet.js:10763:49)
    at s (dotnet.js:8876:64)
    at Object.bindings_lazy_init (dotnet.js:8887:49)
    at Object.bind_static_method (dotnet.js:10849:42)
    at p (dotnet.js:13734:38)
    at boot (dotnet.js:13980:34)
    at async Object.exports.boot (dotnet.js:14138:9)
    at async window.onload (global-module.html:9:9)
```

**Comment by Elringus** [comment] 2022-05-01 17:34
> Making it work in angular

Have you tried `[JSFunction]` stuff? I guess it won't work there as well. Mono-wasm requires a globally-accessible variable to invoke funcs in JS and looks like while this change allows routing the global into the module it's not persisting the assigned objects back.

**Comment by DanielHabenicht** [comment] 2022-05-01 17:50
> > Making it work in angular
> 
> Have you tried `[JSFunction]` stuff? I guess it won't work there as well. Mono-wasm requires a globally-accessible variable to invoke funcs in JS and looks like while this change allows routing the global into the module it's not persisting the assigned objects back.

Yes, I loaded your example.

**Comment by Elringus** [comment] 2022-05-01 18:52
Then I'm probably doing something wrong. I've tried using the getGlobal and self -> this stuff, but it still didn't work with the browser-es example. It's booting but assigned functions are not resolved by the runtime.

**Comment by DanielHabenicht** [comment] 2022-05-01 20:21
maybe it did not come clear from my comment: 

> and at least loading as web module:

which means I am running into the same errors, like `body` is not defined. But at least the loading of the module itself is not erroring. 
I think this maybe has to with web modules effectively enforcing `use strict`.

**Comment by Elringus** [comment] 2022-05-01 23:25
Ok, so I've experimented a bit with migrating the library to es module; rewritten all the JS tests to es-style imports and switched webpack to module output: https://github.com/Elringus/DotNetJS/tree/feat/es-module/JavaScript/dotnet-runtime

I'm currently stuck on how to better wrap the webpack-exported library with the C# packer. Previously I've just [copy-pasted the UMD template](https://github.com/Elringus/DotNetJS/blob/feat/es-module/DotNet/Packer/LibraryGenerator/LibraryTemplate.cs), but now we have to somehow wrap/override the modules exported by webpack. I'm not familiar enough with all that stuff, so any suggestions are most welcome.

**Comment by Aloento** [comment] 2022-05-02 20:55
webpack programmatic api is very useful
https://webpack.js.org/api/node/

**Comment by Elringus** [comment] 2022-05-02 21:28
This will require installing/running webpack when publishing C# project. I'd like to stick with manual patching if possible to simplify the process.

**Comment by Elringus** [comment] 2022-05-03 19:55
It seems manual patching is not feasible after all, given the mess wepback produce with the module target. 

![](https://i.gyazo.com/cd0d8b607f191e1ae6ab1734c6433be5.png)

Will investigate `AspNetCore.NodeServices`.

**Comment by Elringus** [comment] 2022-05-03 20:08
Ah, look like it's deprecated. https://github.com/Elringus/DotNetJS/issues/53

**Comment by Aloento** [comment] 2022-05-09 21:01
Let me work on this.

**Comment by Elringus** [comment] 2022-05-09 21:18
You mean `AspNetCore.NodeServices`? Given it's deprecated, I don't think it's a good idea to rely on this lib.

**Comment by Aloento** [comment] 2022-05-09 21:21
> You mean `AspNetCore.NodeServices`? Given it's deprecated, I don't think it's a good idea to rely on this lib.

I am now working on understanding your `dotnet-runtime` and modifying it for use.

**Comment by Aloento** [comment] 2022-05-09 22:31
[PR](https://github.com/Elringus/DotNetJS/pull/57), please check it

**Comment by promontis** [comment] 2022-08-25 22:28
@Elringus I have a similar problem. I'm using React with NX (webpack) and I got the `global is not defined` error. I override the webpack config to add global to webpack. I now also get `bodyJs is not defined`. 

Did you manage to get it to work in React? If so, did you configure anything special?

**Comment by Elringus** [comment] 2022-08-25 22:56
I'm using it with React, yes. It's a default CRA, w/o any custom building or tooling tweaks. Builds with `react-scripts build`.

**Comment by promontis** [comment] 2022-08-27 14:47
Just tried it... it works with CRA. Had to disable ESLint for the `dotnet.js` file, but that's ok

**Comment by promontis** [comment] 2022-08-27 15:42
@Elringus @Aloento do you know why we sometimes get the `bodyJs is not defined` while we do not get this using CRA?

**Comment by promontis** [comment] 2022-08-28 21:39
For NX it now works if I first create a react app using CRA, and use `cra-to-nx` from NX.

**Comment by Tfermis** [comment] 2022-11-20 21:27
> But running into an error:
> 
> ```shell
> dotnet.js:10763 Uncaught (in promise) ReferenceError: bodyJs is not defined
>     at Object.bind_method (dotnet.js:10763:49)
>     at s (dotnet.js:8876:64)
>     at Object.bindings_lazy_init (dotnet.js:8887:49)
>     at Object.bind_static_method (dotnet.js:10849:42)
>     at p (dotnet.js:13734:38)
>     at boot (dotnet.js:13980:34)
>     at async Object.exports.boot (dotnet.js:14138:9)
>     at async window.onload (global-module.html:9:9)
> ```

Running into this as well for angular... is there a workaround?

**Comment by tuldu** [comment] 2022-11-20 21:32
> But running into an error:
> 
> ```shell
> dotnet.js:10763 Uncaught (in promise) ReferenceError: bodyJs is not defined
>     at Object.bind_method (dotnet.js:10763:49)
>     at s (dotnet.js:8876:64)
>     at Object.bindings_lazy_init (dotnet.js:8887:49)
>     at Object.bind_static_method (dotnet.js:10849:42)
>     at p (dotnet.js:13734:38)
>     at boot (dotnet.js:13980:34)
>     at async Object.exports.boot (dotnet.js:14138:9)
>     at async window.onload (global-module.html:9:9)
> ```

Running into this as well for my angular project... any workaround?

**Comment by DanielHabenicht** [comment] 2022-11-20 22:23
> > But running into an error:
> > 
> > ```shell
> > dotnet.js:10763 Uncaught (in promise) ReferenceError: bodyJs is not defined
> >     at Object.bind_method (dotnet.js:10763:49)
> >     at s (dotnet.js:8876:64)
> >     at Object.bindings_lazy_init (dotnet.js:8887:49)
> >     at Object.bind_static_method (dotnet.js:10849:42)
> >     at p (dotnet.js:13734:38)
> >     at boot (dotnet.js:13980:34)
> >     at async Object.exports.boot (dotnet.js:14138:9)
> >     at async window.onload (global-module.html:9:9)
> > ```
> 
> Running into this as well for my angular project... any workaround?

Yes, try the workaround thats posted at the top the issue (inital issue description): 
> Workaround is adding `(window as any).global = window;` to `polyfill.ts`

**Comment by tuldu** [comment] 2022-11-20 23:02
Yeah, adding this line didn't fix it, unfortunately :(

**Comment by tuldu** [comment] 2022-11-21 06:35
Debugged this a bit more. Had to manually change the syntax in the generated dotnet.js file to get it working

![image](https://user-images.githubusercontent.com/118693629/202932759-3c9e928e-0fce-4ce1-bf6c-82c564c601ed.png)

![image](https://user-images.githubusercontent.com/118693629/202946193-14105b80-6bf8-45c2-921b-aaeeffbf7a92.png)

Is it possible to change Angular to understand this syntax, or generate code with syntax Angular can understand?

**Comment by Elringus** [comment] 2022-11-21 09:02
I'm not familiar with Angular, but regarding changing it on our side: the code comes from .NET's mono-wasm; iirc, they've improved it in .NET 7, so hopefully it'll work after we upgrade (#20). I'll also look into migrating to ES bundler after that.

**Comment by Metrowerks** [comment] 2022-12-01 07:57
> I'm not familiar with Angular, but regarding changing it on our side: the code comes from .NET's mono-wasm; iirc, they've improved it in .NET 7, so hopefully it'll work after we upgrade (#20). I'll also look into migrating to ES bundler after that.

It's not about Angular. It's about the type of Javascript syntax that's generated. The generated JS use implies variable declaration through expressions using commas (see `result` in the screenshot @tuldu attached. This syntax is much less common in JS than explicitly declare the variable with a `var` (as on the modified script on the right side of the screenshot).  [This article discusses similar topic](https://stackoverflow.com/questions/15485735/use-of-commas-versus-semicolons).

Angular doesn't parse this syntax well. I think it should be changed to the more standard and common syntax regardless Angular can parse it or not.

**Comment by jerebtw** [comment] 2023-04-17 06:15
This is also a problem if you want to run the code in deno, since deno does not support umd.

**Closed** 2023-12-31 20:13 UTC
Labels: enhancement, help wanted
